export const GET_PRODUCT_COMMENTS_SUCCEESS = 'GET_PRODUCT_COMMENTS_SUCCEESS'
export const GET_PRODUCT_COMMENTS_FAILED = 'GET_PRODUCT_COMMENTS_FAILED'
export const CLEAR_PRODUCT_COMMENTS = 'CLEAR_PRODUCT_COMMENTS'